import type { FieldValueType } from "@/lib/types";

export interface FieldDefinition {
  key: string;
  label: string;
  valueType: FieldValueType;
  required: boolean;
  note: string;
  aliases: string[];
}

export interface DocumentSchema {
  id: string;
  label: string;
  hints: string[];
  fields: FieldDefinition[];
}

export const SCHEMAS: DocumentSchema[] = [
  {
    id: "invoice",
    label: "Invoice",
    hints: ["invoice", "inv #", "bill to", "total due", "amount due", "qty", "subtotal"],
    fields: [
      {
        key: "vendor",
        label: "Vendor",
        valueType: "org",
        required: true,
        note: "who issued the invoice",
        aliases: ["vendor", "from", "supplier", "company", "org", "bill from"],
      },
      {
        key: "invoice_number",
        label: "Invoice number",
        valueType: "id",
        required: false,
        note: "issuer's invoice identifier",
        aliases: ["invoice #", "invoice number", "inv", "inv no"],
      },
      {
        key: "invoice_date",
        label: "Invoice date",
        valueType: "date",
        required: true,
        note: "date the invoice was issued, not the due date",
        aliases: ["invoice date", "date issued", "issued", "date"],
      },
      {
        key: "due_date",
        label: "Due date",
        valueType: "date",
        required: false,
        note: "when payment is expected",
        aliases: ["due date", "payment due", "due by", "pay by"],
      },
      {
        key: "total_due",
        label: "Total due",
        valueType: "money",
        required: true,
        note: "final amount payable after tax",
        aliases: [
          "total due",
          "amount due",
          "grand total",
          "balance due",
          "total payable",
          "amount payable",
          "total",
        ],
      },
      {
        key: "subtotal",
        label: "Subtotal",
        valueType: "money",
        required: false,
        note: "sum of line items before tax",
        aliases: ["subtotal", "sub total", "net"],
      },
      {
        key: "billing_email",
        label: "Billing email",
        valueType: "email",
        required: false,
        note: "contact for billing questions",
        aliases: ["email", "billing email", "accounts"],
      },
    ],
  },
  {
    id: "receipt",
    label: "Receipt",
    hints: ["receipt", "thank you", "cash", "change", "paid"],
    fields: [
      {
        key: "merchant",
        label: "Merchant",
        valueType: "org",
        required: true,
        note: "store or merchant name",
        aliases: ["merchant", "store", "vendor"],
      },
      {
        key: "purchase_date",
        label: "Purchase date",
        valueType: "date",
        required: true,
        note: "date of the purchase",
        aliases: ["date", "purchased"],
      },
      {
        key: "total_paid",
        label: "Total paid",
        valueType: "money",
        required: true,
        note: "amount charged including tax",
        aliases: ["total", "amount", "paid", "grand total"],
      },
    ],
  },
  {
    id: "resume",
    label: "Resume",
    hints: [
      "experience",
      "education",
      "skills",
      "curriculum",
      "resume",
      "cv",
      "professional summary",
      "professional experience",
      "linkedin.com/in",
      "technical skills",
    ],
    fields: [
      {
        key: "name",
        label: "Name",
        valueType: "person",
        required: true,
        note: "full name at the top of the resume",
        aliases: ["name", "candidate"],
      },
      {
        key: "title",
        label: "Title",
        valueType: "text",
        required: false,
        note: "current role or headline title",
        aliases: ["title", "role", "headline", "engineer"],
      },
      {
        key: "specialization",
        label: "Specialization",
        valueType: "text",
        required: false,
        note: "focus area or stack from the headline",
        aliases: ["specialization", "skills", "stack", "fintech"],
      },
      {
        key: "linkedin",
        label: "Linkedin",
        valueType: "url",
        required: false,
        note: "public LinkedIn profile",
        aliases: ["linkedin", "linkedin.com"],
      },
      {
        key: "email",
        label: "Email",
        valueType: "email",
        required: true,
        note: "contact email",
        aliases: ["email"],
      },
      {
        key: "phone",
        label: "Phone",
        valueType: "phone",
        required: false,
        note: "contact phone",
        aliases: ["phone", "mobile", "tel"],
      },
      {
        key: "location",
        label: "Location",
        valueType: "location",
        required: false,
        note: "city and country",
        aliases: ["location", "based in", "gurugram", "india"],
      },
      {
        key: "years_of_experience",
        label: "Years Of Experience",
        valueType: "text",
        required: false,
        note: "stated years of experience",
        aliases: ["years of experience", "years", "experience"],
      },
    ],
  },
  {
    id: "contract",
    label: "Contract",
    hints: ["agreement", "party", "whereas", "hereinafter", "term of"],
    fields: [
      {
        key: "party",
        label: "Party",
        valueType: "org",
        required: true,
        note: "named organization in the agreement",
        aliases: ["party", "between", "company"],
      },
      {
        key: "effective_date",
        label: "Effective date",
        valueType: "date",
        required: true,
        note: "when the agreement takes effect",
        aliases: ["effective date", "dated", "commencement"],
      },
    ],
  },
  {
    id: "identity",
    label: "Identity Document",
    hints: [
      "aadhaar",
      "passport",
      "driving licence",
      "driver license",
      "government of india",
      "unique identification",
      "uidai",
      "identity card",
      "national id",
      "enrolment no",
      "dob",
    ],
    fields: [
      {
        key: "id_number",
        label: "ID Number",
        valueType: "id",
        required: true,
        note: "the primary unique identifier on the card",
        aliases: ["id number", "id", "aadhaar", "passport no", "license no", "number"],
      },
      {
        key: "full_name",
        label: "Name",
        valueType: "person",
        required: true,
        note: "full name of the document holder",
        aliases: ["name", "holder", "citizen", "candidate"],
      },
      {
        key: "dob",
        label: "Date of Birth",
        valueType: "date",
        required: false,
        note: "date of birth",
        aliases: ["dob", "date of birth", "birth date", "born"],
      },
      {
        key: "gender",
        label: "Gender",
        valueType: "text",
        required: false,
        note: "gender or sex",
        aliases: ["gender", "sex"],
      },
      {
        key: "address",
        label: "Address",
        valueType: "location",
        required: false,
        note: "residential or mailing address",
        aliases: ["address", "residence", "domicile"],
      },
    ],
  },
  {
    id: "tax_financial",
    label: "Financial & Tax Statement",
    hints: [
      "bank statement",
      "account statement",
      "statement of account",
      "form 16",
      "w-2",
      "1099",
      "tax invoice",
      "payslip",
      "salary slip",
      "opening balance",
      "closing balance",
    ],
    fields: [
      {
        key: "account_holder",
        label: "Account Holder",
        valueType: "person",
        required: true,
        note: "account or statement holder name",
        aliases: ["account holder", "name", "customer", "employee"],
      },
      {
        key: "account_number",
        label: "Account Number",
        valueType: "id",
        required: false,
        note: "bank or financial account number",
        aliases: ["account number", "account no", "a/c", "acct"],
      },
      {
        key: "statement_period",
        label: "Statement Period",
        valueType: "date",
        required: false,
        note: "date range or statement date",
        aliases: ["statement period", "period", "date", "statement date"],
      },
      {
        key: "closing_balance",
        label: "Closing Balance",
        valueType: "money",
        required: false,
        note: "ending balance or net pay amount",
        aliases: ["closing balance", "balance", "net pay", "total amount", "amount"],
      },
    ],
  },
  {
    id: "medical",
    label: "Medical & Healthcare Record",
    hints: [
      "prescription",
      "diagnosis",
      "patient",
      "doctor",
      "physician",
      "hospital",
      "clinic",
      "laboratory report",
      "test report",
      "rx",
    ],
    fields: [
      {
        key: "patient_name",
        label: "Patient Name",
        valueType: "person",
        required: true,
        note: "name of the patient",
        aliases: ["patient name", "patient", "name"],
      },
      {
        key: "doctor_name",
        label: "Doctor Name",
        valueType: "person",
        required: false,
        note: "prescribing physician or clinician",
        aliases: ["doctor", "physician", "dr.", "dr"],
      },
      {
        key: "record_date",
        label: "Date",
        valueType: "date",
        required: false,
        note: "date of examination or test",
        aliases: ["date", "consultation date", "visit date"],
      },
      {
        key: "diagnosis",
        label: "Diagnosis",
        valueType: "text",
        required: false,
        note: "findings or diagnosis notes",
        aliases: ["diagnosis", "findings", "impression", "assessment"],
      },
    ],
  },
  {
    id: "certificate",
    label: "Certificate & Credential",
    hints: [
      "certificate of",
      "this is to certify",
      "awarded to",
      "has completed",
      "has successfully completed",
      "diploma",
      "degree of",
      "conferred upon",
    ],
    fields: [
      {
        key: "recipient_name",
        label: "Recipient Name",
        valueType: "person",
        required: true,
        note: "person to whom the certificate was awarded",
        aliases: ["recipient", "awarded to", "name", "certifies that"],
      },
      {
        key: "credential_title",
        label: "Credential Title",
        valueType: "text",
        required: true,
        note: "title of degree, course, or certification",
        aliases: ["degree", "diploma", "certification", "course", "title"],
      },
      {
        key: "issuing_org",
        label: "Issuing Organization",
        valueType: "org",
        required: false,
        note: "university, institute, or organization granting credential",
        aliases: ["organization", "university", "institute", "issuer", "academy"],
      },
      {
        key: "issue_date",
        label: "Issue Date",
        valueType: "date",
        required: false,
        note: "date of award or graduation",
        aliases: ["issue date", "date", "awarded on", "completed on"],
      },
    ],
  },
  {
    id: "generic",
    label: "Generic document",
    hints: [],
    fields: [
      {
        key: "title",
        label: "Title",
        valueType: "text",
        required: false,
        note: "primary heading if one is present",
        aliases: ["title", "subject"],
      },
      {
        key: "primary_date",
        label: "Date",
        valueType: "date",
        required: false,
        note: "the most prominent date on the page",
        aliases: ["date"],
      },
      {
        key: "primary_amount",
        label: "Amount",
        valueType: "money",
        required: false,
        note: "the most prominent currency amount — not assumed to be a total",
        aliases: ["amount", "total"],
      },
    ],
  },
];

export function schemaById(id: string): DocumentSchema {
  return SCHEMAS.find((s) => s.id === id) ?? SCHEMAS[SCHEMAS.length - 1];
}
